### ISSUE TITLE
一直报 没有权限访问资源  确认填写的 id  都是没有问题的

### ISSUE THREAD

**Issue by johnsky123** [serverless-tencent/serverless-tencent-scf#2]
![image](https://user-images.githubusercontent.com/11240977/68364153-180db700-0168-11ea-8051-a8b7294db8cb.png)

**Comment by tinafangkunding** [comment]
收到，这里的角色问题是由于控制台没有访问权限导致的，我们在文档加一下说明。并且优化下控制台的角色授权体验，谢谢反馈！

**Comment by anycodes** [comment]
这个问题产生的原因是没有权限。
可以参考：https://cloud.tencent.com/document/product/583/32389
感谢支持，有问题可以随时提issue

**Comment by johnsky123** [comment]
![image](https://user-images.githubusercontent.com/11240977/68657709-32cc9b00-056f-11ea-9a93-416041b9f64b.png)

我在角色下 添加了这几个访问权限  还是报上图的错误   需要添加哪个载体呢

**Comment by tinafangkunding** [comment]
这边的建议是，您可以先在控制台手动创建一个云函数，会创建这两个角色和对应权限：
![image](https://user-images.githubusercontent.com/26135229/68658792-116cae80-0571-11ea-9843-de93fe244351.png)
之后就可以cli继续部署了。
p.s.这里的问题会在本周之内修复，届时您这边不会再遇到权限的问题，会在部署时cli内支持权限的配置和授权。

**Comment by johnsky123** [comment]
好的   按照上面的方法  解决了   谢谢
