### ISSUE TITLE
Serverless function vpc configuration

### ISSUE THREAD

**Issue by simonobe** [serverless-tencent/serverless-tencent-scf#5]
hello, I have noticed you have a mistake in vpc configuration of your serverless function. Specifically in  deploy/lib/deployFunction.js
Mistake is within `createFunction` function, specifically on lines 84-90
```
if (!_.isEmpty(funcObject.Properties.VpcConfig)) {
	const vpc = funcObject.Properties.VpcConfig;
	createFuncRequest.VpcConfig = {
		VpcId: vpc.vpcId,
		SubnetId: vpc.subnetId
	};
}
```
should be changed to
```
if (!_.isEmpty(funcObject.Properties.VpcConfig)) {
	const vpc = funcObject.Properties.VpcConfig;
	createFuncRequest.VpcConfig = {
		VpcId: vpc.VpcId,
		SubnetId: vpc.SubnetId
	};
}
```
because for some reason Serverless capitalizes all of the properties. I would open up pull request, but since it seems that you  are updating the repo frequently, it would be faster if you would do it.

**Comment by anycodes** [comment]
Thank you, There are two bugs about `vpc`, now I have fixed it.
